version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    labels:
      - "ci"
      - "github-actions"
    rebase-strategy: "auto"